services:
  - name: insighted-app
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/anand-mukul/insighted-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: http://localhost:3000
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_COOKIE
        sync: false
    healthCheckPath: /health
